# Generated by Django 5.2.16 on 2026-07-16 16:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступление')),
            ],
            options={
                'verbose_name': 'Раздел статей',
                'verbose_name_plural': 'Разделы статей',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('intro', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('quote', 5), ('gallery', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Заголовок'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link'], 'label': 'Текст'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иллюстрация'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Цитата'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок врезки', 'max_length': 120, 'required': False}), 7: ('wagtail.blocks.ListBlock', (4,), {'label': 'Фотографии', 'min_num': 1}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('images', 7)]], {})}, verbose_name='Содержание')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
            bases=('wagtailcore.page',),
        ),
    ]
