# Generated by Django 5.2.16 on 2026-07-16 19:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='date',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('quote', 5), ('gallery', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Заголовок'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'superscript', 'subscript'], 'label': 'Текст'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иллюстрация'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Цитата'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок врезки', 'max_length': 120, 'required': False}), 7: ('wagtail.blocks.ListBlock', (4,), {'label': 'Фотографии', 'min_num': 1}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('images', 7)]], {})}, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='cover',
            field=models.ForeignKey(blank=True, help_text='Маленькая картинка в списках статей (на главной и в разделе «Статьи»). Внутри самой статьи не показывается — иллюстрации добавляйте в «Содержание».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Обложка'),
        ),
    ]
