# Generated by Django 5.2.16 on 2026-07-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_commentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Мягкое скрытие для посетителей. Чтобы убрать запись совсем, используйте «Удалить».', verbose_name='Скрыт на сайте'),
        ),
    ]
