# Generated by Django 5.2.16 on 2026-07-18 11:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment_is_deleted_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('quote', 5), ('gallery', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Заголовок'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'h4', 'bold', 'italic', 'underline', 'ol', 'ul', 'hr', 'link', 'superscript', 'subscript'], 'label': 'Текст'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иллюстрация'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Цитата'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок врезки', 'max_length': 120, 'required': False}), 7: ('wagtail.blocks.ListBlock', (4,), {'label': 'Фотографии', 'min_num': 1}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('images', 7)]], {})}, verbose_name='Содержание'),
        ),
    ]
