# Generated by Django 5.2.16 on 2026-07-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_paragraph_underline'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры'),
        ),
        migrations.CreateModel(
            name='ArticleUniqueView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(max_length=64, verbose_name='Ключ посетителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_views', to='articles.articlepage', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Уникальный просмотр статьи',
                'verbose_name_plural': 'Уникальные просмотры статей',
                'constraints': [models.UniqueConstraint(fields=('article', 'visitor_key'), name='unique_article_visitor_view')],
            },
        ),
    ]
