# Generated by Django 5.2.16 on 2026-07-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_favorite_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='cover',
        ),
    ]
