# Generated by Django 5.2.16 on 2026-07-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_date'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryfolderpage',
            name='source_article',
            field=models.OneToOneField(blank=True, help_text='Если заполнено, папка создана автоматически из иллюстраций статьи.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_folder', to='articles.articlepage', verbose_name='Статья-источник'),
        ),
    ]
