# Generated by Django 5.2.16 on 2026-07-18 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressEmailSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Хеш email')),
                ('ciphertext', models.TextField(verbose_name='Шифротекст')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_secret', to='account.emailaddress', verbose_name='Адрес allauth')),
            ],
            options={
                'verbose_name': 'Секрет email адреса',
                'verbose_name_plural': 'Секреты email адресов',
            },
        ),
        migrations.CreateModel(
            name='UserEmailSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Хеш email')),
                ('ciphertext', models.TextField(verbose_name='Шифротекст')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_secret', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Секрет email пользователя',
                'verbose_name_plural': 'Секреты email пользователей',
            },
        ),
    ]
