# Generated by Django 5.2.16 on 2026-07-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры'),
        ),
        migrations.CreateModel(
            name='BlogPostUniqueView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(max_length=64, verbose_name='Ключ посетителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_views', to='blog.blogpost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Уникальный просмотр поста',
                'verbose_name_plural': 'Уникальные просмотры постов',
                'constraints': [models.UniqueConstraint(fields=('post', 'visitor_key'), name='unique_blog_post_visitor_view')],
            },
        ),
    ]
