# Generated by Django 5.2.16 on 2026-07-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_authorpage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='Научный архив', help_text='Название слева вверху, рядом с меню', max_length=120, verbose_name='Текст в шапке (чердак)')),
                ('footer_text', models.CharField(default='Научные материалы и иллюстрации. Сайт-архив.', help_text='Строка внизу каждой страницы', max_length=255, verbose_name='Текст в подвале')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Шапка и подвал',
            },
        ),
    ]
